// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiFarma.Data;

#nullable disable

namespace WikiFarma.Migrations
{
    [DbContext(typeof(WikiFarmaContext))]
    [Migration("20240524110644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WikiFarma.Models.Farmaco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Advertencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Compuesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EdadMinima")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prospecto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TieneReceta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Via")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Farmacos");
                });
#pragma warning restore 612, 618
        }
    }
}
